myapp/models.py
import boto3, os

from itsdangerous import (TimedJSONWebSignatureSerializer
                          as Serializer, BadSignature, SignatureExpired)
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app
from flask_login import LoginManager, UserMixin, login_user, logout_user, current_user
from flask_sqlalchemy import SQLAlchemy

from . import db, login_manager


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), nullable=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))
    socials = db.relationship('OauthUser', backref='user',
                                lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        if self.password_hash:
            return check_password_hash(self.password_hash, password)
        return False

    def __repr__(self):
        return '<User %r>' % self.username

    def generate_auth_token(self, expiration=600):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=expiration)
        return s.dumps({'id': self.id})

    @staticmethod
    def verify_auth_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None    # valid token, but expired
        except BadSignature:
            return None    # invalid token
        user = User.query.get(data['id'])
        return user


class OauthUser(db.Model):
    __tablename__ = 'oauth_users'
    id = db.Column(db.Integer, primary_key=True)
    provider = db.Column(db.String(64), nullable=False)
    social_id = db.Column(db.String(64), nullable=False, unique=True)
    username = db.Column(db.String(64), nullable=True)
    email = db.Column(db.String(64), nullable=True)
    name = db.Column(db.String(64), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))

    
class MyData(db.Model):
    __tablename__ = 'mydata'
    id = db.Column(db.Integer, primary_key=True)
    customer_id = db.Column(db.String(64), unique=True)
    name = db.Column(db.String(64))
    date = db.Column(db.String(20))
    score = db.Column(db.Integer)
    weighting = db.Column(db.Float)

    def __repr__(self):
        return '<MyData %r>' % self.name

    def to_json(self):
        mydata = {
            'customer_id':self.customer_id,
            'name':self.name,
            'date':self.date,
            'score':self.score,
            'weighting':self.weighting
            }
        return mydata

    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

myapp/__init__.py
from flask import Flask, Blueprint
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from config.config import config
from config.secrets import secrets

db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app(config_name):
    """Create an application instance."""
    app = Flask(__name__)

    # apply configuration
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    app.config.from_object(secrets[config_name])

    # initialize extensions
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    
    # register blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from api.v1 import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix="/api")

    return app

myapp/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

myapp/main/views.py
import csv, os

from flask import render_template, request, jsonify, url_for, redirect
from sqlalchemy.sql import text

from .. import db
from . import main
from ..models import MyData

BASEDIR = '/tmp'


@main.route("/")
def index():
    if MyData.query.count():
        return render_template('query.html')
    else:
        return redirect(url_for('main.uploader'))

@main.route("/upload", methods = ['GET','POST'])
def uploader():
    if request.method == 'POST':
        f = request.files['file']
        f.save(os.path.join(BASEDIR, f.filename))
        count = add_db_records(os.path.join(BASEDIR, f.filename))
        str = "<h3>Successfully uploaded file with %d records</h3>" % (count)
        return str + render_template('query.html')
    else: # GET
        return render_template('upload.html')

@main.route("/view")
def view():
    if request.args.get('upload'):
        return redirect(url_for('main.uploader'))

    if request.args.get('delete_all'):
        MyData.query.delete()

    headers = MyData.__table__.columns._data.keys()
    rows = None
    filter = request.args.get('filter', type=str)
    if filter:
        rows = MyData.query.filter(text(filter)).all()
    else:
        rows = MyData.query.all()

    if request.args.get('json'):
        return jsonify([r.to_json() for r in rows])
    else:
        return render_template('view.html', headers=headers, rows=rows, filter=filter)

    
def add_db_records(filename):
    data = []
    with open(filename) as f:
        r = csv.reader(f)
        headers = next(r)
        for row in r:
            d = MyData(**dict(zip(headers,row)))
            data.append(d)
    db.session.add_all(data)
    db.session.commit()
    return len(data)

myapp/templates/base.html
{% import 'macros.html' as macros %}

{% extends "bootstrap/base.html" %}

{% block title %}TestApp{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
	      data-toggle="collapse" data-target=".navbar-collapse">
	<span class="sr-only">Toggle navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.index') }}">TestApp</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
	<li><a href="{{url_for('main.index')}}">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        {% else %}
        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
        {% endif %}
      </ul>
      {% if current_user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
	<li><a>Hi, {{ current_user.username }}!</a></li>
      </ul>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

myapp/templates/macros.html
{% macro render_query(filter) %}

Filter string : <input type="text" name="filter" size="50" value="{{filter}}">
<input type="submit" name="query" value="Run Query">
<input type="submit" name="upload" value="Upload another file">
<input type="submit" name="json" value="JSON Output">
<input type="submit" name="delete_all" value="Delete All" onclick="return confirm('Are you sure you want to delete all records?')">
<br/>
  <dd>
    e.g. leave blank for <a href="{{url_for('main.view', filter='')}}"> all records </a><br/>
    <a href="{{url_for('main.view', filter='1>0 order by score')}}"> all records order by score </a><br/>
    <a href="{{url_for('main.view', filter='id=1')}}"> id=1 </a><br/>
    <a href="{{url_for('main.view', filter="name like '%Peggy%'")}}"> name like '%Peggy%' </a> returns any matches for 'Peggy'<br/>
    <a href="{{url_for('main.view', filter="score>500")}}"> score &gt; 500 </a><br/>
    <a href="{{url_for('main.view', filter="weighting<0.5")}}"> weighting &lt; 0.5 </a><br/>
    <a href="{{url_for('main.view', filter="name like '%Peggy%' and score<100")}}"> name like '%Peggy' and score &lt; 100 </a><br/>
  </dd>

{% endmacro %}

myapp/templates/query.html
{% import 'macros.html' as macros %}
{% extends "base.html" %}
{% block page_content %}
  <form action="{{url_for('main.view')}}" method="GET">
    {{macros.render_query('')}}
  </form>
{% endblock %}

myapp/templates/upload.html
{% extends "base.html" %}
{% block page_content %}
  <form action = "{{url_for('main.uploader')}}" method = "POST"
	enctype = "multipart/form-data">
    <input type = "file" name = "file" />
    <input type = "submit"/>
  </form>
{% endblock %}

myapp/templates/view.html
{% import 'macros.html' as macros %}
{% extends "base.html" %}
{% block title %}Flasky{% endblock %}
{% block scripts %}
{{ super() }}
    <script type="text/javascript" src="{{url_for('static',filename='sorttable.js')}}"></script>
{% endblock %}
{% block styles %}
{{ super() }}
    <style type="text/css">
      /* Sortable tables */
      table.sortable thead {
      background-color: #333;
      color: #cccccc;
      font-weight: bold;
      cursor: default;
      }
      th {
      font-size: 100%;
      }
    </style>
{% endblock %}
{% block page_content %}
    <form action="{{url_for('main.view')}}" method="GET">
      {{macros.render_query(filter)}}
    </form>
    
    <table class="sortable">
      <tr>
	{% for h in headers %}
	<th>{{h}}</th>
	{% endfor %}
      </tr>
      {% if rows|length %}
        {% for r in rows %}
        <tr>
	  {% for h in headers %}
	  <td>{{r|attr(h)}}</td>
	  {% endfor %}
	</tr>
	{% endfor %}
      {% else %}
        <tr><td><b>No Records</b></td></tr>
      {% endif %}
    </table>
{% endblock %}